/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`sp2p6` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `sp2p6`;
/*清空数据表数据*/
truncate table t_agencies;
truncate table t_bid_answers;
truncate table t_bid_questions;
truncate table t_bids;
truncate table t_bill_invests;
truncate table t_bills;
truncate table t_credit_level_audit_items;
truncate table t_dict_banks;
truncate table t_invest_ensure_compensates;
truncate table t_invest_ensure_plans;
truncate table t_invest_transfer_details;
truncate table t_invest_transfers;
truncate table t_invests;
truncate table t_messages;
truncate table t_messages_accepted;
truncate table t_messages_receivers;
truncate table t_platform_details;
truncate table t_statistic_audit_items;
truncate table t_statistic_borrow;
truncate table t_statistic_cps;
truncate table t_statistic_debt_situation;
truncate table t_statistic_financial_situation;
truncate table t_statistic_member;
truncate table t_statistic_platform_float;
truncate table t_statistic_platform_income;
truncate table t_statistic_product;
truncate table t_statistic_recharge;
truncate table t_statistic_security;
truncate table t_statistic_withdraw;
truncate table t_statistic_bill_invest;
truncate table t_statistic_user_audit_items;
truncate table t_system_recharge_completed_sequences;
truncate table t_user_attention_bids;
truncate table t_user_attention_invest_transfers;
truncate table t_user_attention_users;
truncate table t_user_audit_items;
truncate table t_user_automatic_bid;
truncate table t_user_automatic_invest_options;
truncate table t_user_bank_accounts;
truncate table t_user_blacklist;
truncate table t_user_details;
truncate table t_user_details_credit_score;
truncate table t_user_details_score;
truncate table t_user_email_verifying;
truncate table t_user_events;
truncate table t_user_mobile_verifying;
truncate table t_user_over_borrows;
truncate table t_user_recharge_details;
truncate table t_user_report_users;
truncate table t_user_transfer_records;
truncate table t_user_vip_records;
truncate table t_user_withdrawals;
truncate table t_users;
truncate table t_ips_details;
truncate table t_ips_sequences;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;